// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manifest} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ListManifests():Promise<Array<manifest.Manifest>>;
