// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manifest} from '../models';

export function ListManifests():Promise<Array<manifest.Manifest>>;

export function RunManifest(arg1:string,arg2:any):Promise<string>;
