// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListManifests() {
  return window['go']['main']['App']['ListManifests']();
}

export function RunManifest(arg1, arg2) {
  return window['go']['main']['App']['RunManifest'](arg1, arg2);
}
